apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: insecure
  name: insecure
  namespace: secure
spec:
  containers:
  - image: ghcr.io/dsm0014/neo4j:4.2.8-log4shell
    name: insecure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
